spring:
    config:
        import: .env[.properties]
    datasource:
        username: ${db_username}
        password: ${db_password}
        url: jdbc:mysql://${db_ip}:${db_port}/${table_name}?serverTimezone=GMT%2b8
        driver-class-name: com.mysql.cj.jdbc.Driver

    servlet:
        multipart:
            max-file-size: 100MB      # 设置单个文件大小
            max-request-size: 100MB      # 设置单次请求文件的总大小

    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher

oss:
    accessKey: ${accessKey}
    secretKey: ${secretKey}
    bucket: video-peng
    bucket_ts: video-ts
    bucket_m3u8: video-m3u8-peng
    bucket_cover: video-cover

    cdn:
        prefix_m3u8: ${prefix_m3u8}
        prefix_ts: ${prefix_ts}
        prefix_cover: ${prefix_cover}


swagger:
    enable: true  #swagger接口网站开启配置
    basePackage: com.qiniuyun.web_video.controller #基础扫描包范围
    serviceUrl: http://localhost:9099/doc.html  #服务器接口文档访问地址
    contact: 3531057250@qq.com #联系人邮箱
    title: Swagger接口文档  #接口文档标题
    version: v2.1  #接口文档版本
    description: 接口文档查看和接口调试  #接口文档描述

server:
    ip: ${ip}
    port: ${port}


mybatis:
    configuration:
        map-underscore-to-camel-case: true
    mapper-locations:
        classpath: mapper/*.xml
